var searchItems = {
'كلوريد صوديوم 0.225 1/4 ملح طبيعي محلول وريدي 500 مل زجاجة':['0.225% w/v sodium chloride (1/4 normal saline) intravenous infusion bp (500ml bottle) 1 solution for infusion','4.65','sodium chloride','',''],
'كلوريد صوديوم 0.9% محلول وريدي':['0.9% w/v sodium chloride injection b.p 1 solution for injection','1','sodium chloride','',''],
'كلوريد صوديوم 0.9% 1000 مل':['0.9% w/v sodium chloride irrigation usp (1000ml pp bag) 1 irrigation solution','11.6','sodium chloride','',''],
'كلوريد صوديوم 0.9% 2000 مل':['0.9% w/v sodium chloride irrigation usp (2000ml pp bag) 1 irrigation solution','14.05','sodium chloride','',''],
'كلوريد صوديوم 0.9% 250 مل':['0.9% w/v sodium chloride irrigation usp (250ml pp bag) 1 irrigation solution','8.8','sodium chloride','',''],
'كلوريد صوديوم 0.9% 500 مل':['0.9% w/v sodium chloride irrigation usp (500ml pp bag) 1 irrigation solution','10.2','sodium chloride','',''],
'ليدوكايين حقن 1%':['1% w-v lidocaine hcl injection usp 1 solution for injection','6.2','lidocaine (lignocaine) hydrochloride','',''],
'جلايسين 1.5% محلول':['1.5% glycine irrigation usp 1 irrigation solution','26.1','glycine','',''],
'دكستروز 10% - 0.18% كلوريد صوديوم محلول حقن':['10% dextrose and 0.18% sodium chloride usp 1 solution for  injection/infusion','6.6','dextrose, sodium chloride','',''],
'دكستروز 10% - 0.225% كلوريد صوديوم محلول حقن':['10% dextrose and 0.225% sodium chloride usp 1 solution for  injection/infusion','6.75','dextrose, sodium chloride','',''],
'دكستروز 10% - 0.45% كلوريد صوديوم محلول حقن':['10% dextrose and 0.45% sodium chloride usp 1 solution for  injection/infusion','8.45','dextrose, sodium chloride','',''],
'دكستروز 10% - 0.9% كلوريد صوديوم محلول حقن':['10% dextrose and 0.9% sodium chloride usp 1 solution for  injection/infusion','7.95','dextrose, sodium chloride','',''],
'مانيتول محلول وريدي 10%':['10% mannitol intravenous infusion bp 1 solution for injection/infusion','9.95','mannitol','',''],
'بوتاسيوم كلورايد 15% محلول حقن':['15% w-v potassium chloride for inj. usp 1 solution for injection','0.5','potassium chloride','',''],
'ليدوكايين حقن 2 %':['2% w-v lidocaine hcl injection usp 1 solution for injection','6.6','lidocaine (lignocaine) hydrochloride','',''],
'دكستروز 25% محلول حقن 1000 مل':['25% w/v dextrose intravenous infusion usp (1000ml pp bag) 1 solution for infusion','12.6','dextrose','',''],
'دكستروز 25% محلول حقن 250 مل':['25% w/v dextrose intravenous infusion usp (250ml pp bag) 1 solution for infusion','6.75','dextrose','',''],
'دكستروز 25% محلول حقن 500 مل زجاجة':['25% w/v dextrose intravenous infusion usp (500ml pe bottle) 1 solution for infusion','6.6','dextrose','',''],
'دكستروز 25% محلول حقن 500 مل عبوة':['25% w/v dextrose intravenous infusion usp (500ml pp bag) 1 solution for infusion','9.05','dextrose','',''],
'3 في أمبولات':['3v ampoules 3 solution for injection','8.6','vitamin b1 (thiamine), vitamin b2 (riboflavin), vitamin b6 (pyridoxine), nicotinamide, calcium  pantothenol','',''],
'3 في اقراص 20 قرص':['3v tablets 20 tablet','12.4','vitamin b1 (thiamine), vitamin b2 (riboflavin), vitamin b6 (pyridoxine), nicotinamide, calcium  pantothenol','',''],
'دكستروز 4.3% و 0.18% كلوريد صوديوم محلول حقن وريدي':['4.3% dextrose and 0.18% sodium chloride usp 1 solution for infusion','5.45','dextrose, sodium chloride','',''],
'دكستروز 5% و 0.18% كلوريد صوديوم محلول حقن وريدي':['5% dextrose and 0.18% sodium chloride usp 1 solution for  injection/infusion','4.4','dextrose, sodium chloride','',''],
'دكستروز 5% و 0.45% كلوريد صوديوم محلول حقن وريدي':['5% dextrose and 0.45% sodium chloride usp 1 solution for  injection/infusion','5.4','dextrose, sodium chloride','',''],
'دكستروز 50% محلول وريدي 1000 مل عبوة':['50% w/v dextrose intravenous infusion usp (1000ml pp bag) 1 solution for infusion','17.45','dextrose','',''],
'دكستروز 50% محلول وريدي 250 مل عبوة':['50% w/v dextrose intravenous infusion usp (250ml pp bag) 1 solution for infusion','7.75','dextrose','',''],
'دكستروز 50% محلول وريدي 500 مل زجاجة':['50% w/v dextrose intravenous infusion usp (500ml pe bottle) 1 solution for infusion','9.25','dextrose','',''],
'دكستروز 50% محلول وريدي 500 مل عبوة':['50% w/v dextrose intravenous infusion usp (500ml pp bag) 1 solution for infusion','11.9','dextrose','',''],
'ايه زنك جونيور شيكولاتة 50 قرص':['a  zinc  junior  chocolate 50 tablet','34','multivitamins, multi minerals','',''],
'ايه- لاكس 30 قرص':['a- lax 30 tablet','','senna  extract(leaves), rhubarb ( root), cascara sagrada( bark)','',''],
'ابيليفاي 10 مجم 30 قرص':['abilify 10mg tablet 30 tablet','422.15','aripiprazole','',''],
'ابيليفاي 15 مجم 30 قرص':['abilify 15mg tablet 30 tablet','524.5','aripiprazole','',''],
'اكاروز 100 مجم 30 قرص':['acarose 100mg tablets 30 tablet','19.05','acarbose','',''],
'اكاروز 25 مجم 30 قرص':['acarose 25mg tablets 30 tablet','8.85','acarbose','',''],
'اكاروز 50 مجم 30 قرص':['acarose 50mg tablets 30 tablet','15','acarbose','',''],
'ايه سي سي 200 مجم بودرة 20 كيس':['acc 200mg powder for oral solution 20 powder','11.4','acetylcysteine','',''],
'ايه سي سي لونج 600 مجم 10 اقراص فوارة':['acc long 600mg effervescent tablets 10 effervescent tablet','12.55','acetylcysteine','',''],
'اكوليت 20 مجم 30 قرص':['accolate 20 mg f.c.tab 56 tablet','142.5','zafirlukast','',''],
'اكيوزايد 20مجم 30 قرص':['accuzide 20 f.c.tab 30 tablet','77.45','quinapril, hydrochlorothiazide','',''],
'اسيتاب 25 مجم 30 قرص':['acetab 25 mg tablets 30 tablet','20.25','captopril','',''],
'اسيتاب 50 مجم 30 قرص':['acetab 50 mg tablets 30 tablet','34.2','captopril','',''],
'استيل ال كارنيتين 60 كبسولة':['acetyl - l - carnitine capsules 60 capsule','','acetyl-l-carnitine','',''],
'استيل ال كارنيتين 500 مجم 30 كبسولة':['acetyl - l -carnitine 500 30 capsule','','acetyl-l-carnitine','',''],
'استيل سيستايين فوار انستانت 200 مجم 10 اكياس':['acetylcysteine effe instant 200mg sachet 10 granules','5.2','acetylcysteine','',''],
'اسيكال اقراص مضغ 30 قرص':['acical chewable tablets 30 chewable tablet','6','dihydroxy aluminium sodium','',''],
'اسيكال بلس اقراص مضغ 30 قرص':['acical plus chewable tablets 30 chewable tablet','7','dihydroxy aluminum sod. carbonate, simethicone','',''],
'اسيكلين 5% كريم':['aciclin 5% cream 1 cream','20.75','acyclovir (aciclovir)','',''],
'اسيكون اس معلق وحبيبات فوارة':['acicone - s 540mg-5ml susp 1 suspension and effervescent granules for oral  suspension','4.95','magaldrate, simethicon','',''],
'اسيكون اس اقراص مضغ 20 قرص':['acicone - s 720 mg chewable tab 20 chewable tablet','4.95','magaldrate, simethicon','',''],
'اسيكون اقراص مضغ 20 قرص':['acicone 720 mg chewable tab 20 chewable tablet','5.55','magaldrate','',''],
}